I subscribed in https://rapidapi.com/community/api/open-weather-map/ , and get access to the "Climate forecast for 30 days" endpoint and with thisd API I get the climate forecasting of Cairo/Egypt for the coming month â€¢ The API response is e a JSON format contain the following columns/fields: o dt o humidity o pressure o wind_speed o average o average_max o average_min o record_max o record_min

In [1]:
import pandas as pd
import json
import requests

url = "https://community-open-weather-map.p.rapidapi.com/climate/month"

querystring = {"q":"cairo"}

headers = {
    'x-rapidapi-host': "community-open-weather-map.p.rapidapi.com",
    'x-rapidapi-key': "8b63ef84b8msh5618effa460113bp1bda80jsn7eb4acf88e44"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

{"cod":"200","city":{"id":360630,"name":"Cairo","coord":{"lon":31.2497,"lat":30.0626},"country":"EG"},"message":0.418734917,"list":[{"dt":1654300800,"humidity":45.36,"pressure":1011.42,"temp":{"average":301.18,"average_max":307.3,"average_min":295.65,"record_max":316.15,"record_min":288.42},"wind_speed":4.86},{"dt":1654387200,"humidity":50.1,"pressure":1012.42,"temp":{"average":299.7,"average_max":305.59,"average_min":294.32,"record_max":308.88,"record_min":288.22},"wind_speed":4.53},{"dt":1654473600,"humidity":46.76,"pressure":1013.08,"temp":{"average":300.23,"average_max":306.25,"average_min":294.12,"record_max":309.78,"record_min":289.98},"wind_speed":4.6},{"dt":1654560000,"humidity":37.65,"pressure":1012.48,"temp":{"average":301.88,"average_max":308.36,"average_min":294.68,"record_max":312.92,"record_min":292.67},"wind_speed":4.45},{"dt":1654646400,"humidity":43.69,"pressure":1011.05,"temp":{"average":301.39,"average_max":307.76,"average_min":294.97,"record_max":312.15,"record_min":292.03},"wind_speed":4.42},{"dt":1654732800,"humidity":46.8,"pressure":1010.56,"temp":{"average":301.76,"average_max":307.91,"average_min":295.3,"record_max":315.15,"record_min":293.15},"wind_speed":4.35},{"dt":1654819200,"humidity":48.06,"pressure":1011.27,"temp":{"average":301.55,"average_max":307.43,"average_min":295.55,"record_max":311.15,"record_min":292.18},"wind_speed":4.18},{"dt":1654905600,"humidity":47.81,"pressure":1011.38,"temp":{"average":301.57,"average_max":307.63,"average_min":295.47,"record_max":311.5,"record_min":290.79},"wind_speed":4.3},{"dt":1654992000,"humidity":46.45,"pressure":1010.51,"temp":{"average":301.43,"average_max":307.52,"average_min":295.27,"record_max":310.93,"record_min":291.71},"wind_speed":4.82},{"dt":1655078400,"humidity":49.12,"pressure":1009.17,"temp":{"average":301.38,"average_max":307.33,"average_min":295.34,"record_max":311.44,"record_min":290.51},"wind_speed":4.68},{"dt":1655164800,"humidity":50.39,"pressure":1009.43,"temp":{"average":301.2,"average_max":306.92,"average_min":294.94,"record_max":313.15,"record_min":290.39},"wind_speed":4.19},{"dt":1655251200,"humidity":47.34,"pressure":1010.39,"temp":{"average":301.75,"average_max":307.36,"average_min":295.74,"record_max":313.15,"record_min":291.75},"wind_speed":4.03},{"dt":1655337600,"humidity":44.88,"pressure":1010.47,"temp":{"average":302.02,"average_max":308.02,"average_min":295.53,"record_max":311.39,"record_min":291.49},"wind_speed":4.61},{"dt":1655424000,"humidity":47.78,"pressure":1010.67,"temp":{"average":301.95,"average_max":308.3,"average_min":295.68,"record_max":314.5,"record_min":291.99},"wind_speed":4.8},{"dt":1655510400,"humidity":48.92,"pressure":1010.23,"temp":{"average":301.9,"average_max":307.62,"average_min":295.49,"record_max":311.15,"record_min":291.85},"wind_speed":4.08},{"dt":1655596800,"humidity":46.39,"pressure":1009.55,"temp":{"average":302.42,"average_max":308.3,"average_min":296.61,"record_max":310.58,"record_min":293.83},"wind_speed":4.23},{"dt":1655683200,"humidity":46.79,"pressure":1010.21,"temp":{"average":302.31,"average_max":308.1,"average_min":295.95,"record_max":309.97,"record_min":291.93},"wind_speed":4.3},{"dt":1655769600,"humidity":44.28,"pressure":1010.81,"temp":{"average":302.64,"average_max":308.56,"average_min":295.89,"record_max":313.15,"record_min":292.1},"wind_speed":3.96},{"dt":1655856000,"humidity":48.92,"pressure":1011.02,"temp":{"average":302.43,"average_max":308.51,"average_min":296.52,"record_max":312.15,"record_min":291.62},"wind_speed":4.19},{"dt":1655942400,"humidity":53.79,"pressure":1011.19,"temp":{"average":302.07,"average_max":307.95,"average_min":296.09,"record_max":311.98,"record_min":292.08},"wind_speed":4.44},{"dt":1656028800,"humidity":54.01,"pressure":1010.66,"temp":{"average":301.73,"average_max":307.62,"average_min":296.02,"record_max":309.99,"record_min":291.19},"wind_speed":4.36},{"dt":1656115200,"humidity":53.82,"pressure":1009.9,"temp":{"average":301.83,"average_max":307.88,"average_min":295.75,"record_max":311.03,"record_min":290},"wind_speed":4.14},{"dt":1656201600,"humidity":49.85,"pressure":1009.42,"temp":{"average":302.74,"average_max":309.03,"average_min":296.49,"record_max":312.09,"record_min":293.42},"wind_speed":4.22},{"dt":1656288000,"humidity":47.78,"pressure":1008.55,"temp":{"average":303.62,"average_max":310.23,"average_min":297.28,"record_max":315.15,"record_min":295.42},"wind_speed":4.2},{"dt":1656374400,"humidity":52.69,"pressure":1009.2,"temp":{"average":302.48,"average_max":308.15,"average_min":296.84,"record_max":313.15,"record_min":294.98},"wind_speed":4.14},{"dt":1656460800,"humidity":52.15,"pressure":1009.2,"temp":{"average":302.49,"average_max":308.57,"average_min":296.46,"record_max":311.75,"record_min":293.28},"wind_speed":3.88},{"dt":1656547200,"humidity":53.73,"pressure":1009.42,"temp":{"average":302.25,"average_max":307.98,"average_min":296.23,"record_max":311.88,"record_min":294.32},"wind_speed":3.84},{"dt":1656633600,"humidity":53.36,"pressure":1009.66,"temp":{"average":302.54,"average_max":308.17,"average_min":296.69,"record_max":312.57,"record_min":294.47},"wind_speed":3.98},{"dt":1656720000,"humidity":50.4,"pressure":1009.46,"temp":{"average":303.16,"average_max":308.89,"average_min":297.33,"record_max":314.1,"record_min":295.05},"wind_speed":3.88},{"dt":1656806400,"humidity":50.56,"pressure":1008.79,"temp":{"average":302.95,"average_max":308.67,"average_min":297.16,"record_max":314.1,"record_min":295.15},"wind_speed":3.85}]}

In [2]:
data=json.loads(response.text)

In [3]:
df_from_API = pd.DataFrame(json.loads(response.text)['list'])
df_from_API.head(2)

,dt,humidity,pressure,temp,wind_speed
0,1654300800,45.36,1011.42,"{'average': 301.18, 'average_max': 307.3, 'ave...",4.86
1,1654387200,50.10,1012.42,"{'average': 299.7, 'average_max': 305.59, 'ave...",4.53

In [4]:
df_from_API = pd.concat([df_from_API, pd.json_normalize(df_from_API['temp'])], axis=1)
df_from_API = df_from_API.rename(columns={'average': 'temp_average', 'average_max': 'temp_average_max', 'average_min': 'temp_average_min',
                                'record_max': 'temp_record_max', 'record_min': 'temp_record_min'})
df_from_API.head(2)

,dt,humidity,pressure,temp,wind_speed,temp_average,temp_average_max,temp_average_min,temp_record_max,temp_record_min
0,1654300800,45.36,1011.42,"{'average': 301.18, 'average_max': 307.3, 'ave...",4.86,301.18,307.30,295.65,316.15,288.42
1,1654387200,50.10,1012.42,"{'average': 299.7, 'average_max': 305.59, 'ave...",4.53,299.70,305.59,294.32,308.88,288.22

In [5]:
del df_from_API['temp']
df_from_API.head()

,dt,humidity,pressure,wind_speed,temp_average,temp_average_max,temp_average_min,temp_record_max,temp_record_min
0,1654300800,45.36,1011.42,4.86,301.18,307.30,295.65,316.15,288.42
1,1654387200,50.10,1012.42,4.53,299.70,305.59,294.32,308.88,288.22
2,1654473600,46.76,1013.08,4.60,300.23,306.25,294.12,309.78,289.98
3,1654560000,37.65,1012.48,4.45,301.88,308.36,294.68,312.92,292.67
4,1654646400,43.69,1011.05,4.42,301.39,307.76,294.97,312.15,292.03